[project]
name = "auth-service"
version = "0.0.0"
description = "Микросервис аутентификации для платформы ExRateHub, отвечающий за регистрацию пользователей, вход, управление API-ключами и выдачу JWT-токенов."
readme = "README.md"
authors = [
    { name = "SharinAlex", email = "alex.shavrin200303@gmail.com" },
    { name = "theVeenrok", email = "veenrok@veenrok.com" },
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.1",
    "granian>=2.3.1",
    "litestar>=2.16.0",
    "psycopg[binary]>=3.2.9",
    "pydantic[email]>=2.11.5",
    "pydantic-settings>=2.9.1",
    "sqlalchemy[asyncio]>=2.0.41",
    "pwdlib[argon2]>=0.2.1",
    "pyjwt>=2.10.1",
    "redis[hiredis]>=6.1.0",
    "aiosmtplib>=4.0.1",
    "dishka>=1.6.0",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "ruff>=0.11.11",
    "granian[reload]>=2.3.1",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "pre-commit>=4.2.0",
    "black>=25.1.0",
    "sqlalchemy[mypy]>=2.0.41",
    "isort>=6.0.1",
]

[tool.mypy]
python_version = 3.13
ignore_missing_imports = true
strict = true
files = ["src", "tests"]
allow_redefinition = false
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]

[tool.pydantic-mypy]
init_forbid_extra = false
init_typed = true

[tool.ruff]
line-length = 99
fix = true

[tool.black]
line-length = 99
target-version = ["py313"]

[tool.isort]
profile = "black"
line_length = 99
known_first_party = ["auth_service"]
sections = ["STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
multi_line_output = 3

[lint.ignore]
ignore = ["E203", "W503"]

[lint.select]
select = ["E", "F", "W", "C90", "I"]
