"""Rename password_hash to hashed_password

Revision ID: eb5a05dda6e4
Revises: 4ba7d64948cd
Create Date: 2025-05-27 03:29:33.247907

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb5a05dda6e4"
down_revision: Union[str, None] = "4ba7d64948cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.Text(), nullable=False))
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password_hash", sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
